name: Test CLI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -e . && pip install manim python-dotenv
      - run: animateitnow "Draw a simple triangle" --no-render
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
